<?php
namespace App;

use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    const SEX_UN = 10;//WEIZHI
    const SEX_BOY = 20;//boy
    const SEX_GRIL = 30;//gril

    protected $table = 'student';

    public $timestamps = true;

    protected $fillable = ['name','age','sex'];

    protected function getDateFormat()
    {
//        return parent::getDateFormat(); // TODO: Change the autogenerated stub
        return time();          //use unix time
    }

    protected function asDateTime($value)
    {
//        return parent::asDateTime($value); // TODO: Change the autogenerated stub
        return $value;          //use unix time
    }

    public function sex($ind = null)
    {
        $arr =[
            self::SEX_UN => "未知",
            self::SEX_BOY => "男",
            self::SEX_GRIL => "女"
        ];
        if ($ind != null){
            return array_key_exists($ind,$arr) ? $arr[$ind] : $arr[self::SEX_UN];
        }
        return $arr;
    }

}